name: CI-CD

env:
  S3_BUCKET_NAME: "github-php"
  EB_APPLICATION_NAME: "php"
  EB_ENVIRONMENT_NAME: "Php-env"
  DEPLOY_PACKAGE_NAME: "php_from_github_${{ github.sha }}.zip"
  AWS_REGION: "eu-central-1"

on:
  push:
    branches:
      - master
    paths:
      - php/**

jobs:
  ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: Clone apt repo
        uses: actions/checkout@v1

      - name: Create Zip
        run: zip -rj ${{ env.DEPLOY_PACKAGE_NAME }} ${{ env.EB_APPLICATION_NAME}} -x *.git*

      - name: Configure my AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy package to S3 BUCKET
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.S3_BUCKET_NAME }}

      - name: Print CI Finish
        run: echo "CI Finished"

  cd-part:
    runs-on: ubuntu-latest
    needs: [ci_part]
        
    steps:
      - name: Configure my AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create new EB APP
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ env.EB_APPLICATION_NAME }} \
          --source-bundle S3Bucket="${{ env.S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
          --version-label "Ver-${{ github.sha }}" \
          --description "CommitSHA-${{ github.sha }}"

      - name: Deploy new EB APP Version
        run: aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "Ver-${{ github.sha }}"

      - name: Print CD Finish
        run: echo "CD Finished"